### ISSUE TITLE
Incorrect Control behavior 

### ISSUE THREAD

**Issue by Virusnest** [sm64pc/sm64pc#461]
Mario is stuck Crounching, Start is Bound to my triggers and R does not work so I cant change configs Ingame

 - OS: Retropie 
 - Version 7.1
 - Controler XBOX 360

Instaled Via retropie Extras
Note: ROM region was checked before compilation

**Comment by Virusnest** [comment]
I recently found out that controls on keyboard work

**Comment by fgsfdsfgs** [comment]
Download [this file](https://raw.githubusercontent.com/gabomdq/SDL_GameControllerDB/master/gamecontrollerdb.txt) and put it either next to the sm64ex executable or into `~/.local/share/sm64ex/`.
If that doesn't work, either rebind controls by manually editing `~/.local/share/sm64ex/sm64config.txt` or generate a control mapping for your gamepad with [this tool](https://www.generalarcade.com/gamepadtool/) and use the resulting `gamecontrollerdb.txt` file instead of the one I linked above.
