### ISSUE TITLE
sm64.us.f3dex2e looks for assets in absolute paths

### ISSUE THREAD

**Issue by superbonaci** [sm64pc/sm64pc#480]
Moved the entire folder `build/us_pc/` to another location, now `sm64.us.f3dex2e` doesn't launch:
```
FATAL ERROR:
could not load sound data from 'sound/sequences.bin'
```
If I keep a copy of the assets in previous location it works, so the game looks for absolute fixed paths.
Could be possible to make binary relative to assets folders, or just incorporate all assets within the binary file?

**Comment by fgsfdsfgs** [comment]
It shouldn't look in absolute paths, it looks next to the executable by default. What does it say if you run it from a terminal?
I think what's happening is you either forgot to move the `res` folder or it just isn't there, and there happens to be a duplicate of `sound/sequences.bin` and other files in the `build/us_pc` folder, because it gets later added to a data archive.
Though that still doesn't make much sense, since you say you've moved the entire folder.

**Comment by superbonaci** [comment]
My mistake. It works, but the binary standalone doesn't. I have the entire `sm64ex` build folder. How can I know which files are necessary to run the game and clean up all the unnecessary source code, just the required file?

**Comment by fgsfdsfgs** [comment]
Just the EXE and the `res` folder are necessary, everything else isn't. If you want a completely self contained package, build without `EXTERNAL_DATA`.

**Comment by superbonaci** [comment]
Thanks, works perfect, but you must clean before making again:
```
cd sm64ex
make clean
make distclean
make EXTERNAL_DATA=0 BETTERCAMERA=1 EXT_OPTIONS_MENU=1
```
