### ISSUE TITLE
Recompiling gives errors, even when 

### ISSUE THREAD

**Issue by ghost** [sm64pc/sm64pc#510]
**Describe the bug**
When recompiling, I get error 127

**To Reproduce**
1. Use make command to compile.
2. Attempt to recompile with different settings
3. Error
4. Delete old build
5. Attempt to recompile again
6: Same error
**Expected behavior**
What I expected was it to recompile with my new settings.

**Screenshots**
```
make: Entering directory '/home/hobbi/sm64ex/tools'
make: Nothing to be done for 'default'.
make: Leaving directory '/home/hobbi/sm64ex/tools'
make: sdl2-config: No such file or directory
make: sdl2-config: No such file or directory
cpp -P -DVERSION_US -D_LANGUAGE_C -DNIGHTLY -DGIT_HASH="\"db9a634\"" -DNON_MATCHING -DAVOID_UB -I . -o build/us_pc/level_rules.mk levels/level_rules.mk
/bin/sh: line 1: cpp: command not found
Makefile.split:152: build/us_pc/level_rules.mk: No such file or directory
make: *** [Makefile.split:151: build/us_pc/level_rules.mk] Error 127
```

**Desktop (please complete the following information):**
 -OS: Windows 11 21H2

**Comment by fgsfdsfgs** [comment]
You don't seem to have gcc installed. If this is in MSYS2, ensure that you're in the MINGW64 (or 32) prompt and execute  
```pacman -S unzip make git mingw-w64-i686-gcc mingw-w64-x86_64-gcc mingw-w64-i686-glew mingw-w64-x86_64-glew mingw-w64-i686-SDL2 mingw-w64-i686-SDL mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL python3```
then try again. If you're in WSL2, you should try [using MSYS2](https://github.com/sm64pc/sm64ex/wiki/Compiling-on-Windows) instead, since cross-compiling from WSL2 is a pain in the ass.
I'll close this since it's been a long time, but feel free to reopen if you need more help.
