### ISSUE TITLE
Can't Replace Mario's Model.

### ISSUE THREAD

**Issue by avereyishere** [sm64pc/sm64pc#539]
**Describe the bug**
A Compiling Error When I Try And Replace Mario's Model With Fast64

**To Reproduce**
Get Blender
Get Fast64
Get Yoshi Milkman's [Mario Model](https://cdn.discordapp.com/attachments/755907254318006362/998620420330762380/Yoshi_Milkmans_Mario_Model_Blend.zip)
Export It Into sm64ex

**Expected behavior**
Game Compiles Fine And The Model Get's Replaced.

**Screenshots**
![image](https://github.com/sm64pc/sm64ex/assets/109289447/e1429398-cc49-43b6-a721-d647a985d507)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Browser Firefox
 - Version 119.0.1

**Additional context**
My PC Is A Chromebook 11 G8 EE

**Comment by fgsfdsfgs** [comment]
It requires some manual work to integrate, I would assume, because it looks like it's missing the textures. Either that or you have to build (or not build) with `EXTERNAL_DATA=1`. In any case, I can't really help you with that since that's a mod that wasn't made by me, maybe someone in the SM64PC Discord can help.
