### ISSUE TITLE
Border flickering on menu transitions flickering with non 4:3 aspect ratio

### ISSUE THREAD

**Issue by r4dius** [sm64pc/sm64pc#73]
Hi, when the fade to / from white transitions to / from menu occur, there's a small flicker to black on the borders over 4:3 image, I've been testing the script.c and geo.c logic for the level select menu but can't identify the cause yet,
testing on opengl pc / switch, haven't tried directx btw :/

**Comment by r4dius** [comment]
You guys got it fixed here https://github.com/sm64pc/sm64pc/commit/d2cff2838f79f82fb2f50bb7e9e234b5437cc053 :)

**Comment by dernett** [comment]
Hmmm, I'm still getting flickering. Is it working for you?

**Comment by r4dius** [comment]
Yeah my bad, it actually fixed a glitch with black borders (on switch) but the flickering is still there, btw for some reason it's fixed on the code that spread from unknow (?) source with the first public exe floating around, just can't figure out what's the fix as it seems it's old code and lot's of changes have been done since

**Comment by dernett** [comment]
That's interesting. I've actually done some snooping around and it seems that the issue is caused from this line which runs during the warp transition https://github.com/sm64pc/sm64pc/blob/d2cff2838f79f82fb2f50bb7e9e234b5437cc053/src/game/area.c#L418
Instead of drawing a filled rectangle with the proper aspect ratio, it always seems to draw a rectangle with a 4:3 aspect ratio. I think the issue could be caused from these two lines https://github.com/sm64pc/sm64pc/blob/d2cff2838f79f82fb2f50bb7e9e234b5437cc053/src/pc/gfx/gfx_pc.c#L1115-L1116 but not totally sure.

**Comment by dernett** [comment]
I was able to get it working! It turns out the correct gDPFillRectangle command already exists in this function. https://github.com/sm64pc/sm64pc/blob/d2cff2838f79f82fb2f50bb7e9e234b5437cc053/src/game/rendering_graph_node.c#L519-L520 So we just need to replace these lines https://github.com/sm64pc/sm64pc/blob/d2cff2838f79f82fb2f50bb7e9e234b5437cc053/src/game/game_init.c#L155-L156
with these lines
```C
    gDPFillRectangle(gDisplayListHead++, GFX_DIMENSIONS_RECT_FROM_LEFT_EDGE(0), BORDER_HEIGHT,
        GFX_DIMENSIONS_RECT_FROM_RIGHT_EDGE(0) - 1, SCREEN_HEIGHT - BORDER_HEIGHT - 1);
```
and include gfx_dimensions.h for the macros.

**Comment by Hyenadae** [comment]
Thanks! I'll add this to my repo and ask for it to be merged.

**Comment by Hyenadae** [comment]
Hey, did you get any errors while compiling? I included gfx_dimensions but 

src/game/game_init.c:158:5: note: in expansion of macro ‘gDPFillRectangle’
     gDPFillRectangle(gDisplayListHead++, GFX_DIMENSIONS_RECT_FROM_LEFT_EDGE(0), BORDER_HEIGHT,
     ^~~~~~~~~~~~~~~~
include/PR/gbi.h:4402:10: note: each undeclared identifier is reported only once for each function it appears in
          _SHIFTL((lrx), 2, 22);    \
          ^~~~~~~
src/game/game_init.c:158:5: note: in expansion of macro ‘gDPFillRectangle’
     gDPFillRectangle(gDisplayListHead++, GFX_DIMENSIONS_RECT_FROM_LEFT_EDGE(0), BORDER_HEIGHT,
     ^~~~~~~~~~~~~~~~

**Comment by dernett** [comment]
It compiled fine for me, here's my commit cf4eb18866bfa2e312ad0053bbbc1a83236a0926.

**Comment by Hyenadae** [comment]
I... forgot a parenthesis at the end of the ((int) addition to the border define fix. I also fixed up my N64 build removal work and now it's compiling fine!

**Comment by Hyenadae** [comment]
https://github.com/sm64pc/sm64pc/pull/86/commits

Alright. Just gotta wait for a maintainer to look it over and put it in

**Comment by r4dius** [comment]
Nice one, thanks it works perfectly :)

**Comment by r4dius** [comment]
> I was able to get it working! It turns out the correct gDPFillRectangle command already exists in this function.
> 
> https://github.com/sm64pc/sm64pc/blob/d2cff2838f79f82fb2f50bb7e9e234b5437cc053/src/game/rendering_graph_node.c#L519-L520
> 
> So we just need to replace these lines
> https://github.com/sm64pc/sm64pc/blob/d2cff2838f79f82fb2f50bb7e9e234b5437cc053/src/game/game_init.c#L155-L156
> 
> 
> with these lines
> ```c
>     gDPFillRectangle(gDisplayListHead++, GFX_DIMENSIONS_RECT_FROM_LEFT_EDGE(0), BORDER_HEIGHT,
>         GFX_DIMENSIONS_RECT_FROM_RIGHT_EDGE(0) - 1, SCREEN_HEIGHT - BORDER_HEIGHT - 1);
> ```
> 
> and include gfx_dimensions.h for the macros.

the same exact line is present on clear_z_buffer function at line 133, would it be useful to replace it too ?

**Comment by coltongit** [comment]
Would be worth a look into that particular line again. I'll look at it in the morn.

**Comment by coltongit** [comment]
Alright, got the line changed in PR #233.

**Comment by r4dius** [comment]
Thanks :), closing this now
